### PR TITLE
Bug fixing from #917

### LINKED ISSUE #853: Hidden interiors like toyota_base can spawn in redecoration

### LINKED ISSUE #887: The player can still pick the TARDIS with HADS activated
This shouldn't happen

### PR DESCRIPTION
**Pull request by parar020100**
Since the vertical falling feature is not ready yet, I'd suggest these changes to be merged first.
They fix a whole bunch of problems, as described by the commits.
Perhaps a minor release could be in place?

P.S. most of these changes have been reviewed in #917
I've fixed comments to that PR (apart from the falling)

### CODE REVIEW

File: lua/tardis/controls/sh_control_float.lua [hunk 1]
```diff
@@ -8,7 +8,7 @@ TARDIS:AddControl({
         end
     end,
     serveronly=true,
-    power_independent = false,
+    power_independent = true,
```
Comment (AmyJeanes) [inline lua/tardis/controls/sh_control_float.lua:11]: Not sure I get why we changed this because it will still fail with power off anyway just with a different message?

File: lua/entities/gmod_tardis/modules/sh_health.lua [hunk 2]
```diff
@@ -15,33 +15,54 @@ ENT:AddHook("SettingChanged","maxhealth-changed", function(self, id, val)
...
+    self:CallCommonHook("OnHealthChange", new_health, old_health)
+    if new_health == 0 and old_health ~= 0 then
+        self:CallCommonHook("OnHealthDepleted")
     end
-    self:SetData("health-val", newhealth, true)
-    self:CallCommonHook("OnHealthChange", newhealth, oldhealth)
+end
+
+if SERVER then
+    ENT:OnMessage("health_change", function(self, data, ply)
```
Comment (AmyJeanes) [inline lua/entities/gmod_tardis/modules/sh_health.lua]: This doesn't appear to have any kind of security around it and anyone running clientside scripts could change the TARDIS health at any time

File: lua/entities/gmod_tardis/modules/sh_health.lua [hunk 3]
```diff
@@ -15,33 +15,54 @@ ENT:AddHook("SettingChanged","maxhealth-changed", function(self, id, val)
...
 
 function ENT:GetHealth()
     return self:GetData("health-val", 0)
 end
 
+function ENT:IsAlive()
+    return (self:GetHealth() ~= 0)
+end
+
+function ENT:GetRepairPrimed()
```
Comment (AmyJeanes) [inline lua/entities/gmod_tardis/modules/sh_health.lua:48]: This code is duplicated from fixes already made in dev for both `GetRepairPrimed` and `GetRepairing`

File: lua/entities/gmod_tardis/modules/sv_handbrake.lua [hunk 4]
```diff
@@ -28,9 +28,9 @@ ENT:AddHook("ShouldFailDemat", "handbrake", function(self, force)
 end)
 
 ENT:AddHook("HandbrakeToggled", "vortex", function(self, on)
-    if on and self:GetData("teleport") or self:GetData("vortex") then
+    if on and (self:GetData("teleport") or self:GetData("vortex")) then
```
Comment (AmyJeanes) [inline lua/entities/gmod_tardis/modules/sv_handbrake.lua]: Would be easier to read if we return early `if not on` rather than this

File: lua/tardis/controls/sh_control_teleport.lua [hunk 5]
```diff
@@ -27,7 +27,7 @@ TARDIS:AddControl({
     end,
     serveronly=true,
     power_independent = false,
-    bypass_console_toggle = true,
+    bypass_console_toggle = false,
```
Comment (AmyJeanes) [inline lua/tardis/controls/sh_control_teleport.lua]: Might as well just remove these lines rather than having them to false on this and the double teleport control

File: lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua [hunk 6]
```diff
@@ -23,7 +23,7 @@ function ENT:ToggleFastRemat()
 end
 
 function ENT:SetFastRemat(on, force)
-    if (not force) and (self:CallHook("CanToggleFastRemat") == false) then
+    if self:CallHook("CanToggleFastRemat", force) == false then
```
Comment (AmyJeanes) [inline lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua:26]: These changes are not required as redecoration was fixed in a different way already

**Review by AmyJeanes — CHANGES_REQUESTED** [review]

File: lua/tardis/controls/sh_control_float.lua (hunk 1 above)
Comment (parar020100) [reply lua/tardis/controls/sh_control_float.lua:11]: I haven't found any reasons for it to fail in the code
Will test though

The point of the change is to allow the player to **disable** anti-gravs when powered-down

So if you mean the `CanTurnOnFloat` hook, that's okay since there's no `CanTurnOffFloat` hook

File: lua/entities/gmod_tardis/modules/sh_health.lua (hunk 2 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/sh_health.lua]: right
I think we need to make `ChangeHealth` completely serverside, idk why it was being called from a client anyway

File: lua/entities/gmod_tardis/modules/sh_health.lua (hunk 3 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/sh_health.lua:48]: Rebase conflict, my bad

File: lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua (hunk 6 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua:26]: where and how was it fixed?

File: lua/tardis/controls/sh_control_float.lua (hunk 1 above)
Comment (parar020100) [reply lua/tardis/controls/sh_control_float.lua:11]: **UPD**: double-checked, you can disable anti-gravs when power is disabled
that was the goal
not turning on but turning off (so that you don't get stuck)

File: lua/tardis/controls/sh_control_teleport.lua (hunk 5 above)
Comment (parar020100) [reply lua/tardis/controls/sh_control_teleport.lua]: b70f996f3de524374052efcd1b117246cdb24335

File: lua/entities/gmod_tardis/modules/sh_health.lua (hunk 3 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/sh_health.lua:48]: 9115edec229fd2a660e9f7d8946ec6f94d1ef27f

File: lua/entities/gmod_tardis/modules/sv_handbrake.lua (hunk 4 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/sv_handbrake.lua]: makes sense
8f56cf4a5a6392263641bc9f306fb854932b7440

File: lua/entities/gmod_tardis/modules/sh_health.lua (hunk 2 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/sh_health.lua]: done
9115edec229fd2a660e9f7d8946ec6f94d1ef27f

File: lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua (hunk 6 above)
Comment (parar020100) [reply lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua:26]: I believe it is better within the `CenToggleFastRemat` hook since even though we are restricting it for teleport/vortex, there might be other restrictions that don't even apply to force fast remat toggle

Comment (AmyJeanes) [reply lua/entities/gmod_tardis/modules/teleport/sh_tp_vortex.lua:26]: Makes sense to me, no harm in doing this just thought worth noting

File: lua/tardis/controls/sh_control_float.lua (hunk 1 above)
Comment (AmyJeanes) [reply lua/tardis/controls/sh_control_float.lua:11]: Ah okay gotcha, didn't realise that was the reason I just tried turning it on

**Review by AmyJeanes — APPROVED** [review]
Thank you! Nice work
